name: news_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/business.jpg
    - assets/entertaiment.jpg
    - assets/general.jpg
    - assets/health.jpg
    - assets/science.jpg
    - assets/sports.jpg
    - assets/technology.jpg
